/* tslint:disable */
/* eslint-disable */
/**
 * E-Commerce project
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AddToCartDto {
    /**
     * The ID of the product to add to the cart
     */
    'productId': string;
    /**
     * The quantity of the product to add
     */
    'quantity': number;
}
export interface CartItemResponseDto {
    'id': string;
    'cartId': string;
    'productId': string;
    'quantity': number;
    'priceSnapshot': string;
    'createdAt': string;
    'updatedAt': string;
}
export interface CartResponseDto {
    'id': string;
    'userId'?: string | null;
    'sessionId'?: string | null;
    'status': string;
    'items': Array<CartItemResponseDto>;
    'createdAt': string;
    'updatedAt': string;
}
export interface LoginRequestDto {
    /**
     * The email address of the user
     */
    'email': string;
    /**
     * The password for the user account
     */
    'password': string;
}
export interface PaginatedProductResponseDto {
    'data': Array<ProductResponseDto>;
    'meta': PaginationMetaDto;
}
export interface PaginationMetaDto {
    'total': number;
    'page': number;
    'limit': number;
}
export interface ProductResponseDto {
    'id': string;
    'productName': string;
    'description'?: object;
    'imageUrl'?: object;
    'imagePublicId'?: object;
    'price': object;
    'stock': number;
    'offerPercentage'?: object;
    'isActive': object;
    'soldBy'?: object;
    'promotionLabel'?: object;
    'brand'?: object;
    'ingredients'?: object;
    'rating'?: object;
    'tags'?: Array<string>;
    'specialFor'?: object;
    'categoryId'?: object;
    'createdAt': string;
    'updatedAt'?: object;
}
export interface RegisterRequestDto {
    /**
     * The name of the user
     */
    'name': string;
    /**
     * The mobile number of the user
     */
    'mobileNumber': string;
    /**
     * The email address of the user
     */
    'email': string;
    /**
     * The password for the user account
     */
    'password': string;
}
export interface UpdateCartItemDto {
    /**
     * The new quantity for the cart item
     */
    'quantity': number;
}
export interface UpdateProductDto {
    'productName'?: string;
    'description'?: string;
    'price'?: number;
    'stock'?: number;
    'brand'?: string;
    'soldBy'?: string;
    'ingredients'?: string;
    'specialFor'?: string;
    'tags'?: Array<string>;
    'offerPercentage'?: number;
    'imageUrl'?: string;
    'imagePublicId'?: string;
}
export interface UpdateStatusDto {
    /**
     * Set product active status
     */
    'isActive': boolean;
}
export interface UpdateStockDto {
    /**
     * New stock quantity
     */
    'stock': number;
}
export interface UserResponseDto {
    /**
     * The unique identifier of the user
     */
    'id': string;
    /**
     * The name of the user
     */
    'name': string;
    /**
     * The email address of the user
     */
    'email': string;
}

/**
 * CartApi - axios parameter creator
 */
export const CartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Mark cart as abandoned
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAbandonCart: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerAbandonCart', 'id', id)
            const localVarPath = `/api/carts/{id}/abandon`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds a product to the cart or updates quantity if it already exists
         * @summary Add item to cart
         * @param {AddToCartDto} addToCartDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAddCart: async (addToCartDto: AddToCartDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addToCartDto' is not null or undefined
            assertParamExists('cartControllerAddCart', 'addToCartDto', addToCartDto)
            const localVarPath = `/api/carts/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addToCartDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes all items and resets the cart
         * @summary Clear entire cart
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerClearCart: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerClearCart', 'id', id)
            const localVarPath = `/api/carts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the current cart for the user or guest session
         * @summary Get current cart session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerGetCart: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/carts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark cart as ordered
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerMarkAsOrdered: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerMarkAsOrdered', 'id', id)
            const localVarPath = `/api/carts/{id}/order`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes a specific cart item by its ID
         * @summary Remove item from cart
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerRemoveItem: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerRemoveItem', 'id', id)
            const localVarPath = `/api/carts/item/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update cart item quantity
         * @param {string} id 
         * @param {UpdateCartItemDto} updateCartItemDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerUpdateCartItem: async (id: string, updateCartItemDto: UpdateCartItemDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerUpdateCartItem', 'id', id)
            // verify required parameter 'updateCartItemDto' is not null or undefined
            assertParamExists('cartControllerUpdateCartItem', 'updateCartItemDto', updateCartItemDto)
            const localVarPath = `/api/carts/item/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCartItemDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CartApi - functional programming interface
 */
export const CartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CartApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Mark cart as abandoned
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerAbandonCart(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerAbandonCart(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerAbandonCart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Adds a product to the cart or updates quantity if it already exists
         * @summary Add item to cart
         * @param {AddToCartDto} addToCartDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerAddCart(addToCartDto: AddToCartDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CartItemResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerAddCart(addToCartDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerAddCart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes all items and resets the cart
         * @summary Clear entire cart
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerClearCart(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerClearCart(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerClearCart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the current cart for the user or guest session
         * @summary Get current cart session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerGetCart(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CartResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerGetCart(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerGetCart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Mark cart as ordered
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerMarkAsOrdered(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerMarkAsOrdered(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerMarkAsOrdered']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes a specific cart item by its ID
         * @summary Remove item from cart
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerRemoveItem(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerRemoveItem(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerRemoveItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update cart item quantity
         * @param {string} id 
         * @param {UpdateCartItemDto} updateCartItemDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerUpdateCartItem(id: string, updateCartItemDto: UpdateCartItemDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CartItemResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerUpdateCartItem(id, updateCartItemDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.cartControllerUpdateCartItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CartApi - factory interface
 */
export const CartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CartApiFp(configuration)
    return {
        /**
         * 
         * @summary Mark cart as abandoned
         * @param {CartApiCartControllerAbandonCartRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAbandonCart(requestParameters: CartApiCartControllerAbandonCartRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cartControllerAbandonCart(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Adds a product to the cart or updates quantity if it already exists
         * @summary Add item to cart
         * @param {CartApiCartControllerAddCartRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAddCart(requestParameters: CartApiCartControllerAddCartRequest, options?: RawAxiosRequestConfig): AxiosPromise<CartItemResponseDto> {
            return localVarFp.cartControllerAddCart(requestParameters.addToCartDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes all items and resets the cart
         * @summary Clear entire cart
         * @param {CartApiCartControllerClearCartRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerClearCart(requestParameters: CartApiCartControllerClearCartRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cartControllerClearCart(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the current cart for the user or guest session
         * @summary Get current cart session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerGetCart(options?: RawAxiosRequestConfig): AxiosPromise<CartResponseDto> {
            return localVarFp.cartControllerGetCart(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark cart as ordered
         * @param {CartApiCartControllerMarkAsOrderedRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerMarkAsOrdered(requestParameters: CartApiCartControllerMarkAsOrderedRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cartControllerMarkAsOrdered(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes a specific cart item by its ID
         * @summary Remove item from cart
         * @param {CartApiCartControllerRemoveItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerRemoveItem(requestParameters: CartApiCartControllerRemoveItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cartControllerRemoveItem(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update cart item quantity
         * @param {CartApiCartControllerUpdateCartItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerUpdateCartItem(requestParameters: CartApiCartControllerUpdateCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CartItemResponseDto> {
            return localVarFp.cartControllerUpdateCartItem(requestParameters.id, requestParameters.updateCartItemDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cartControllerAbandonCart operation in CartApi.
 */
export interface CartApiCartControllerAbandonCartRequest {
    readonly id: string
}

/**
 * Request parameters for cartControllerAddCart operation in CartApi.
 */
export interface CartApiCartControllerAddCartRequest {
    readonly addToCartDto: AddToCartDto
}

/**
 * Request parameters for cartControllerClearCart operation in CartApi.
 */
export interface CartApiCartControllerClearCartRequest {
    readonly id: string
}

/**
 * Request parameters for cartControllerMarkAsOrdered operation in CartApi.
 */
export interface CartApiCartControllerMarkAsOrderedRequest {
    readonly id: string
}

/**
 * Request parameters for cartControllerRemoveItem operation in CartApi.
 */
export interface CartApiCartControllerRemoveItemRequest {
    readonly id: string
}

/**
 * Request parameters for cartControllerUpdateCartItem operation in CartApi.
 */
export interface CartApiCartControllerUpdateCartItemRequest {
    readonly id: string

    readonly updateCartItemDto: UpdateCartItemDto
}

/**
 * CartApi - object-oriented interface
 */
export class CartApi extends BaseAPI {
    /**
     * 
     * @summary Mark cart as abandoned
     * @param {CartApiCartControllerAbandonCartRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerAbandonCart(requestParameters: CartApiCartControllerAbandonCartRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerAbandonCart(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds a product to the cart or updates quantity if it already exists
     * @summary Add item to cart
     * @param {CartApiCartControllerAddCartRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerAddCart(requestParameters: CartApiCartControllerAddCartRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerAddCart(requestParameters.addToCartDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes all items and resets the cart
     * @summary Clear entire cart
     * @param {CartApiCartControllerClearCartRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerClearCart(requestParameters: CartApiCartControllerClearCartRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerClearCart(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the current cart for the user or guest session
     * @summary Get current cart session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerGetCart(options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerGetCart(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark cart as ordered
     * @param {CartApiCartControllerMarkAsOrderedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerMarkAsOrdered(requestParameters: CartApiCartControllerMarkAsOrderedRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerMarkAsOrdered(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes a specific cart item by its ID
     * @summary Remove item from cart
     * @param {CartApiCartControllerRemoveItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerRemoveItem(requestParameters: CartApiCartControllerRemoveItemRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerRemoveItem(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update cart item quantity
     * @param {CartApiCartControllerUpdateCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cartControllerUpdateCartItem(requestParameters: CartApiCartControllerUpdateCartItemRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerUpdateCartItem(requestParameters.id, requestParameters.updateCartItemDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProductsApi - axios parameter creator
 */
export const ProductsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productName 
         * @param {string} description 
         * @param {number} price 
         * @param {number} stock 
         * @param {string} categoryId 
         * @param {File} [image] Product image file (optional)
         * @param {string} [brand] 
         * @param {ProductControllerCreateProductPromotionLabelEnum} [promotionLabel] 
         * @param {string} [soldBy] 
         * @param {string} [ingredients] 
         * @param {string} [specialFor] 
         * @param {number} [offerPercentage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerCreateProduct: async (productName: string, description: string, price: number, stock: number, categoryId: string, image?: File, brand?: string, promotionLabel?: ProductControllerCreateProductPromotionLabelEnum, soldBy?: string, ingredients?: string, specialFor?: string, offerPercentage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productName' is not null or undefined
            assertParamExists('productControllerCreateProduct', 'productName', productName)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('productControllerCreateProduct', 'description', description)
            // verify required parameter 'price' is not null or undefined
            assertParamExists('productControllerCreateProduct', 'price', price)
            // verify required parameter 'stock' is not null or undefined
            assertParamExists('productControllerCreateProduct', 'stock', stock)
            // verify required parameter 'categoryId' is not null or undefined
            assertParamExists('productControllerCreateProduct', 'categoryId', categoryId)
            const localVarPath = `/api/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }

            if (productName !== undefined) { 
                localVarFormParams.append('productName', productName as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            if (price !== undefined) { 
                localVarFormParams.append('price', price as any);
            }

            if (stock !== undefined) { 
                localVarFormParams.append('stock', stock as any);
            }

            if (categoryId !== undefined) { 
                localVarFormParams.append('categoryId', categoryId as any);
            }

            if (brand !== undefined) { 
                localVarFormParams.append('brand', brand as any);
            }

            if (promotionLabel !== undefined) { 
                localVarFormParams.append('promotionLabel', promotionLabel as any);
            }

            if (soldBy !== undefined) { 
                localVarFormParams.append('soldBy', soldBy as any);
            }

            if (ingredients !== undefined) { 
                localVarFormParams.append('ingredients', ingredients as any);
            }

            if (specialFor !== undefined) { 
                localVarFormParams.append('specialFor', specialFor as any);
            }

            if (offerPercentage !== undefined) { 
                localVarFormParams.append('offerPercentage', offerPercentage as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Admin endpoint: returns all products regardless of active status
         * @summary [Admin] Get all products including inactive
         * @param {string} [search] Search by product name (ILIKE)
         * @param {string} [categoryId] Filter by category UUID
         * @param {ProductControllerGetAdminProductsPromotionLabelEnum} [promotionLabel] Promotion Label
         * @param {number} [minPrice] Minimum price filter
         * @param {number} [maxPrice] Maximum price filter
         * @param {ProductControllerGetAdminProductsSortByEnum} [sortBy] 
         * @param {ProductControllerGetAdminProductsOrderEnum} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetAdminProducts: async (search?: string, categoryId?: string, promotionLabel?: ProductControllerGetAdminProductsPromotionLabelEnum, minPrice?: number, maxPrice?: number, sortBy?: ProductControllerGetAdminProductsSortByEnum, order?: ProductControllerGetAdminProductsOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/products/admin/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (categoryId !== undefined) {
                localVarQueryParameter['categoryId'] = categoryId;
            }

            if (promotionLabel !== undefined) {
                localVarQueryParameter['promotionLabel'] = promotionLabel;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['minPrice'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['maxPrice'] = maxPrice;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns paginated active products with optional filters (search, category, price range, sorting)
         * @summary Get all active products
         * @param {string} [search] Search by product name (ILIKE)
         * @param {string} [categoryId] Filter by category UUID
         * @param {ProductControllerGetAllProductsPromotionLabelEnum} [promotionLabel] Promotion Label
         * @param {number} [minPrice] Minimum price filter
         * @param {number} [maxPrice] Maximum price filter
         * @param {ProductControllerGetAllProductsSortByEnum} [sortBy] 
         * @param {ProductControllerGetAllProductsOrderEnum} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetAllProducts: async (search?: string, categoryId?: string, promotionLabel?: ProductControllerGetAllProductsPromotionLabelEnum, minPrice?: number, maxPrice?: number, sortBy?: ProductControllerGetAllProductsSortByEnum, order?: ProductControllerGetAllProductsOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (categoryId !== undefined) {
                localVarQueryParameter['categoryId'] = categoryId;
            }

            if (promotionLabel !== undefined) {
                localVarQueryParameter['promotionLabel'] = promotionLabel;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['minPrice'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['maxPrice'] = maxPrice;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single active product by its UUID
         * @summary Get product by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetProductById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productControllerGetProductById', 'id', id)
            const localVarPath = `/api/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sets isActive = false. Product is hidden from public listings but not removed from DB.
         * @summary [Admin] Soft delete a product
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerSoftDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productControllerSoftDelete', 'id', id)
            const localVarPath = `/api/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Partial update of any product field
         * @summary [Admin] Update a product
         * @param {string} id 
         * @param {UpdateProductDto} updateProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateProduct: async (id: string, updateProductDto: UpdateProductDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productControllerUpdateProduct', 'id', id)
            // verify required parameter 'updateProductDto' is not null or undefined
            assertParamExists('productControllerUpdateProduct', 'updateProductDto', updateProductDto)
            const localVarPath = `/api/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProductDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Activate or deactivate a product without deleting it
         * @summary [Admin] Toggle product active/inactive status
         * @param {string} id 
         * @param {UpdateStatusDto} updateStatusDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateStatus: async (id: string, updateStatusDto: UpdateStatusDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productControllerUpdateStatus', 'id', id)
            // verify required parameter 'updateStatusDto' is not null or undefined
            assertParamExists('productControllerUpdateStatus', 'updateStatusDto', updateStatusDto)
            const localVarPath = `/api/products/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateStatusDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Directly set the stock quantity for a product
         * @summary [Admin] Update product stock
         * @param {string} id 
         * @param {UpdateStockDto} updateStockDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateStock: async (id: string, updateStockDto: UpdateStockDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productControllerUpdateStock', 'id', id)
            // verify required parameter 'updateStockDto' is not null or undefined
            assertParamExists('productControllerUpdateStock', 'updateStockDto', updateStockDto)
            const localVarPath = `/api/products/{id}/stock`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateStockDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductsApi - functional programming interface
 */
export const ProductsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productName 
         * @param {string} description 
         * @param {number} price 
         * @param {number} stock 
         * @param {string} categoryId 
         * @param {File} [image] Product image file (optional)
         * @param {string} [brand] 
         * @param {ProductControllerCreateProductPromotionLabelEnum} [promotionLabel] 
         * @param {string} [soldBy] 
         * @param {string} [ingredients] 
         * @param {string} [specialFor] 
         * @param {number} [offerPercentage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerCreateProduct(productName: string, description: string, price: number, stock: number, categoryId: string, image?: File, brand?: string, promotionLabel?: ProductControllerCreateProductPromotionLabelEnum, soldBy?: string, ingredients?: string, specialFor?: string, offerPercentage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerCreateProduct(productName, description, price, stock, categoryId, image, brand, promotionLabel, soldBy, ingredients, specialFor, offerPercentage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerCreateProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Admin endpoint: returns all products regardless of active status
         * @summary [Admin] Get all products including inactive
         * @param {string} [search] Search by product name (ILIKE)
         * @param {string} [categoryId] Filter by category UUID
         * @param {ProductControllerGetAdminProductsPromotionLabelEnum} [promotionLabel] Promotion Label
         * @param {number} [minPrice] Minimum price filter
         * @param {number} [maxPrice] Maximum price filter
         * @param {ProductControllerGetAdminProductsSortByEnum} [sortBy] 
         * @param {ProductControllerGetAdminProductsOrderEnum} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerGetAdminProducts(search?: string, categoryId?: string, promotionLabel?: ProductControllerGetAdminProductsPromotionLabelEnum, minPrice?: number, maxPrice?: number, sortBy?: ProductControllerGetAdminProductsSortByEnum, order?: ProductControllerGetAdminProductsOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerGetAdminProducts(search, categoryId, promotionLabel, minPrice, maxPrice, sortBy, order, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerGetAdminProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns paginated active products with optional filters (search, category, price range, sorting)
         * @summary Get all active products
         * @param {string} [search] Search by product name (ILIKE)
         * @param {string} [categoryId] Filter by category UUID
         * @param {ProductControllerGetAllProductsPromotionLabelEnum} [promotionLabel] Promotion Label
         * @param {number} [minPrice] Minimum price filter
         * @param {number} [maxPrice] Maximum price filter
         * @param {ProductControllerGetAllProductsSortByEnum} [sortBy] 
         * @param {ProductControllerGetAllProductsOrderEnum} [order] 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerGetAllProducts(search?: string, categoryId?: string, promotionLabel?: ProductControllerGetAllProductsPromotionLabelEnum, minPrice?: number, maxPrice?: number, sortBy?: ProductControllerGetAllProductsSortByEnum, order?: ProductControllerGetAllProductsOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerGetAllProducts(search, categoryId, promotionLabel, minPrice, maxPrice, sortBy, order, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerGetAllProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a single active product by its UUID
         * @summary Get product by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerGetProductById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerGetProductById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerGetProductById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sets isActive = false. Product is hidden from public listings but not removed from DB.
         * @summary [Admin] Soft delete a product
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerSoftDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerSoftDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerSoftDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Partial update of any product field
         * @summary [Admin] Update a product
         * @param {string} id 
         * @param {UpdateProductDto} updateProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerUpdateProduct(id: string, updateProductDto: UpdateProductDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerUpdateProduct(id, updateProductDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerUpdateProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Activate or deactivate a product without deleting it
         * @summary [Admin] Toggle product active/inactive status
         * @param {string} id 
         * @param {UpdateStatusDto} updateStatusDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerUpdateStatus(id: string, updateStatusDto: UpdateStatusDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerUpdateStatus(id, updateStatusDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerUpdateStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Directly set the stock quantity for a product
         * @summary [Admin] Update product stock
         * @param {string} id 
         * @param {UpdateStockDto} updateStockDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productControllerUpdateStock(id: string, updateStockDto: UpdateStockDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productControllerUpdateStock(id, updateStockDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productControllerUpdateStock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProductsApi - factory interface
 */
export const ProductsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductsApiFp(configuration)
    return {
        /**
         * 
         * @param {ProductsApiProductControllerCreateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerCreateProduct(requestParameters: ProductsApiProductControllerCreateProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productControllerCreateProduct(requestParameters.productName, requestParameters.description, requestParameters.price, requestParameters.stock, requestParameters.categoryId, requestParameters.image, requestParameters.brand, requestParameters.promotionLabel, requestParameters.soldBy, requestParameters.ingredients, requestParameters.specialFor, requestParameters.offerPercentage, options).then((request) => request(axios, basePath));
        },
        /**
         * Admin endpoint: returns all products regardless of active status
         * @summary [Admin] Get all products including inactive
         * @param {ProductsApiProductControllerGetAdminProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetAdminProducts(requestParameters: ProductsApiProductControllerGetAdminProductsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedProductResponseDto> {
            return localVarFp.productControllerGetAdminProducts(requestParameters.search, requestParameters.categoryId, requestParameters.promotionLabel, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.sortBy, requestParameters.order, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns paginated active products with optional filters (search, category, price range, sorting)
         * @summary Get all active products
         * @param {ProductsApiProductControllerGetAllProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetAllProducts(requestParameters: ProductsApiProductControllerGetAllProductsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedProductResponseDto> {
            return localVarFp.productControllerGetAllProducts(requestParameters.search, requestParameters.categoryId, requestParameters.promotionLabel, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.sortBy, requestParameters.order, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single active product by its UUID
         * @summary Get product by ID
         * @param {ProductsApiProductControllerGetProductByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerGetProductById(requestParameters: ProductsApiProductControllerGetProductByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productControllerGetProductById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Sets isActive = false. Product is hidden from public listings but not removed from DB.
         * @summary [Admin] Soft delete a product
         * @param {ProductsApiProductControllerSoftDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerSoftDelete(requestParameters: ProductsApiProductControllerSoftDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productControllerSoftDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Partial update of any product field
         * @summary [Admin] Update a product
         * @param {ProductsApiProductControllerUpdateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateProduct(requestParameters: ProductsApiProductControllerUpdateProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productControllerUpdateProduct(requestParameters.id, requestParameters.updateProductDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Activate or deactivate a product without deleting it
         * @summary [Admin] Toggle product active/inactive status
         * @param {ProductsApiProductControllerUpdateStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateStatus(requestParameters: ProductsApiProductControllerUpdateStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productControllerUpdateStatus(requestParameters.id, requestParameters.updateStatusDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Directly set the stock quantity for a product
         * @summary [Admin] Update product stock
         * @param {ProductsApiProductControllerUpdateStockRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productControllerUpdateStock(requestParameters: ProductsApiProductControllerUpdateStockRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productControllerUpdateStock(requestParameters.id, requestParameters.updateStockDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for productControllerCreateProduct operation in ProductsApi.
 */
export interface ProductsApiProductControllerCreateProductRequest {
    readonly productName: string

    readonly description: string

    readonly price: number

    readonly stock: number

    readonly categoryId: string

    /**
     * Product image file (optional)
     */
    readonly image?: File

    readonly brand?: string

    readonly promotionLabel?: ProductControllerCreateProductPromotionLabelEnum

    readonly soldBy?: string

    readonly ingredients?: string

    readonly specialFor?: string

    readonly offerPercentage?: number
}

/**
 * Request parameters for productControllerGetAdminProducts operation in ProductsApi.
 */
export interface ProductsApiProductControllerGetAdminProductsRequest {
    /**
     * Search by product name (ILIKE)
     */
    readonly search?: string

    /**
     * Filter by category UUID
     */
    readonly categoryId?: string

    /**
     * Promotion Label
     */
    readonly promotionLabel?: ProductControllerGetAdminProductsPromotionLabelEnum

    /**
     * Minimum price filter
     */
    readonly minPrice?: number

    /**
     * Maximum price filter
     */
    readonly maxPrice?: number

    readonly sortBy?: ProductControllerGetAdminProductsSortByEnum

    readonly order?: ProductControllerGetAdminProductsOrderEnum

    readonly page?: number

    readonly limit?: number
}

/**
 * Request parameters for productControllerGetAllProducts operation in ProductsApi.
 */
export interface ProductsApiProductControllerGetAllProductsRequest {
    /**
     * Search by product name (ILIKE)
     */
    readonly search?: string

    /**
     * Filter by category UUID
     */
    readonly categoryId?: string

    /**
     * Promotion Label
     */
    readonly promotionLabel?: ProductControllerGetAllProductsPromotionLabelEnum

    /**
     * Minimum price filter
     */
    readonly minPrice?: number

    /**
     * Maximum price filter
     */
    readonly maxPrice?: number

    readonly sortBy?: ProductControllerGetAllProductsSortByEnum

    readonly order?: ProductControllerGetAllProductsOrderEnum

    readonly page?: number

    readonly limit?: number
}

/**
 * Request parameters for productControllerGetProductById operation in ProductsApi.
 */
export interface ProductsApiProductControllerGetProductByIdRequest {
    readonly id: string
}

/**
 * Request parameters for productControllerSoftDelete operation in ProductsApi.
 */
export interface ProductsApiProductControllerSoftDeleteRequest {
    readonly id: string
}

/**
 * Request parameters for productControllerUpdateProduct operation in ProductsApi.
 */
export interface ProductsApiProductControllerUpdateProductRequest {
    readonly id: string

    readonly updateProductDto: UpdateProductDto
}

/**
 * Request parameters for productControllerUpdateStatus operation in ProductsApi.
 */
export interface ProductsApiProductControllerUpdateStatusRequest {
    readonly id: string

    readonly updateStatusDto: UpdateStatusDto
}

/**
 * Request parameters for productControllerUpdateStock operation in ProductsApi.
 */
export interface ProductsApiProductControllerUpdateStockRequest {
    readonly id: string

    readonly updateStockDto: UpdateStockDto
}

/**
 * ProductsApi - object-oriented interface
 */
export class ProductsApi extends BaseAPI {
    /**
     * 
     * @param {ProductsApiProductControllerCreateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerCreateProduct(requestParameters: ProductsApiProductControllerCreateProductRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerCreateProduct(requestParameters.productName, requestParameters.description, requestParameters.price, requestParameters.stock, requestParameters.categoryId, requestParameters.image, requestParameters.brand, requestParameters.promotionLabel, requestParameters.soldBy, requestParameters.ingredients, requestParameters.specialFor, requestParameters.offerPercentage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Admin endpoint: returns all products regardless of active status
     * @summary [Admin] Get all products including inactive
     * @param {ProductsApiProductControllerGetAdminProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerGetAdminProducts(requestParameters: ProductsApiProductControllerGetAdminProductsRequest = {}, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerGetAdminProducts(requestParameters.search, requestParameters.categoryId, requestParameters.promotionLabel, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.sortBy, requestParameters.order, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns paginated active products with optional filters (search, category, price range, sorting)
     * @summary Get all active products
     * @param {ProductsApiProductControllerGetAllProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerGetAllProducts(requestParameters: ProductsApiProductControllerGetAllProductsRequest = {}, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerGetAllProducts(requestParameters.search, requestParameters.categoryId, requestParameters.promotionLabel, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.sortBy, requestParameters.order, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single active product by its UUID
     * @summary Get product by ID
     * @param {ProductsApiProductControllerGetProductByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerGetProductById(requestParameters: ProductsApiProductControllerGetProductByIdRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerGetProductById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sets isActive = false. Product is hidden from public listings but not removed from DB.
     * @summary [Admin] Soft delete a product
     * @param {ProductsApiProductControllerSoftDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerSoftDelete(requestParameters: ProductsApiProductControllerSoftDeleteRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerSoftDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Partial update of any product field
     * @summary [Admin] Update a product
     * @param {ProductsApiProductControllerUpdateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerUpdateProduct(requestParameters: ProductsApiProductControllerUpdateProductRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerUpdateProduct(requestParameters.id, requestParameters.updateProductDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Activate or deactivate a product without deleting it
     * @summary [Admin] Toggle product active/inactive status
     * @param {ProductsApiProductControllerUpdateStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerUpdateStatus(requestParameters: ProductsApiProductControllerUpdateStatusRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerUpdateStatus(requestParameters.id, requestParameters.updateStatusDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Directly set the stock quantity for a product
     * @summary [Admin] Update product stock
     * @param {ProductsApiProductControllerUpdateStockRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productControllerUpdateStock(requestParameters: ProductsApiProductControllerUpdateStockRequest, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productControllerUpdateStock(requestParameters.id, requestParameters.updateStockDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ProductControllerCreateProductPromotionLabelEnum = {
    newArrival: 'New Arrival',
    bestSeller: 'Best Seller',
    clearance: 'Clearance',
    hotDeal: 'Hot Deal',
    limitedEdition: 'Limited Edition',
} as const;
export type ProductControllerCreateProductPromotionLabelEnum = typeof ProductControllerCreateProductPromotionLabelEnum[keyof typeof ProductControllerCreateProductPromotionLabelEnum];
export const ProductControllerGetAdminProductsPromotionLabelEnum = {
    newArrival: 'NEW_ARRIVAL',
    bestSeller: 'BEST_SELLER',
    clearance: 'CLEARANCE',
    hotDeal: 'HOT_DEAL',
    limitedEdition: 'LIMITED_EDITION',
} as const;
export type ProductControllerGetAdminProductsPromotionLabelEnum = typeof ProductControllerGetAdminProductsPromotionLabelEnum[keyof typeof ProductControllerGetAdminProductsPromotionLabelEnum];
export const ProductControllerGetAdminProductsSortByEnum = {
    price: 'price',
    rating: 'rating',
    createdAt: 'createdAt',
} as const;
export type ProductControllerGetAdminProductsSortByEnum = typeof ProductControllerGetAdminProductsSortByEnum[keyof typeof ProductControllerGetAdminProductsSortByEnum];
export const ProductControllerGetAdminProductsOrderEnum = {
    asc: 'asc',
    desc: 'desc',
} as const;
export type ProductControllerGetAdminProductsOrderEnum = typeof ProductControllerGetAdminProductsOrderEnum[keyof typeof ProductControllerGetAdminProductsOrderEnum];
export const ProductControllerGetAllProductsPromotionLabelEnum = {
    newArrival: 'NEW_ARRIVAL',
    bestSeller: 'BEST_SELLER',
    clearance: 'CLEARANCE',
    hotDeal: 'HOT_DEAL',
    limitedEdition: 'LIMITED_EDITION',
} as const;
export type ProductControllerGetAllProductsPromotionLabelEnum = typeof ProductControllerGetAllProductsPromotionLabelEnum[keyof typeof ProductControllerGetAllProductsPromotionLabelEnum];
export const ProductControllerGetAllProductsSortByEnum = {
    price: 'price',
    rating: 'rating',
    createdAt: 'createdAt',
} as const;
export type ProductControllerGetAllProductsSortByEnum = typeof ProductControllerGetAllProductsSortByEnum[keyof typeof ProductControllerGetAllProductsSortByEnum];
export const ProductControllerGetAllProductsOrderEnum = {
    asc: 'asc',
    desc: 'desc',
} as const;
export type ProductControllerGetAllProductsOrderEnum = typeof ProductControllerGetAllProductsOrderEnum[keyof typeof ProductControllerGetAllProductsOrderEnum];


/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all active users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetAllUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login a user
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLogin: async (loginRequestDto: LoginRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequestDto' is not null or undefined
            assertParamExists('userControllerLogin', 'loginRequestDto', loginRequestDto)
            const localVarPath = `/api/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {RegisterRequestDto} registerRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerRegister: async (registerRequestDto: RegisterRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRequestDto' is not null or undefined
            assertParamExists('userControllerRegister', 'registerRequestDto', registerRequestDto)
            const localVarPath = `/api/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all active users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerGetAllUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetAllUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerGetAllUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerGetMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerGetMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login a user
         * @param {LoginRequestDto} loginRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerLogin(loginRequestDto: LoginRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerLogin(loginRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a new user
         * @param {RegisterRequestDto} registerRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerRegister(registerRequestDto: RegisterRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerRegister(registerRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerRegister']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all active users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetAllUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserResponseDto>> {
            return localVarFp.userControllerGetAllUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerGetMe(options?: RawAxiosRequestConfig): AxiosPromise<UserResponseDto> {
            return localVarFp.userControllerGetMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login a user
         * @param {UserApiUserControllerLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLogin(requestParameters: UserApiUserControllerLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userControllerLogin(requestParameters.loginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserApiUserControllerRegisterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerRegister(requestParameters: UserApiUserControllerRegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponseDto> {
            return localVarFp.userControllerRegister(requestParameters.registerRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for userControllerLogin operation in UserApi.
 */
export interface UserApiUserControllerLoginRequest {
    readonly loginRequestDto: LoginRequestDto
}

/**
 * Request parameters for userControllerRegister operation in UserApi.
 */
export interface UserApiUserControllerRegisterRequest {
    readonly registerRequestDto: RegisterRequestDto
}

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Get all active users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userControllerGetAllUsers(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerGetAllUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userControllerGetMe(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerGetMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login a user
     * @param {UserApiUserControllerLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userControllerLogin(requestParameters: UserApiUserControllerLoginRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerLogin(requestParameters.loginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {UserApiUserControllerRegisterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userControllerRegister(requestParameters: UserApiUserControllerRegisterRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerRegister(requestParameters.registerRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}



